import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { Aboreto } from "next/font/google";
import "./globals.css";
import Header from "@/components/app_components/header";
import Footer from "@/components/app_components/footer";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const aboreto = Aboreto({
  variable: "--font-aboreto",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Aladam Dental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.variable} ${aboreto.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
