import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { Aboreto } from "next/font/google";
import "./globals.css";
import Header from "@/components/app_components/header";
import Footer from "@/components/app_components/footer";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const aboreto = Aboreto({
  variable: "--font-aboreto",
  weight: "400",
});

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;

  return {
    title: `Aladam Dental | ${locale}`,
    description: "Generated by create next app",
  };
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const messages = await getMessages();
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${jost.variable} ${aboreto.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
